### ISSUE TITLE
tergmlite dev branch performance assessment

### ISSUE THREAD

**Issue by martinamorris** [statnet/tergmLite#25]
Initial work on this is unfortunately spread across #23 and #24:

@smjenness found problems using the new tergmlite on a het network test https://github.com/statnet/tergmLite/issues/23#issuecomment-527934703

@chad-klumb reproduced, 
https://github.com/statnet/tergmLite/issues/24#issuecomment-528075759

using the packages (ergm pre API levels change)  installed by Sam's script: https://github.com/EpiModel/CombPrev/blob/master/InstallStack.R

Let's use this issue to follow up.

**Comment by chad-klumb** [comment]
I would say I did *not* reproduce those results.

The MPLE took ~ 20 minutes both with `dev` and with those older versions linked to in the other issue.

Since MCMC didn't converge I don't think we should try comparing those runtimes; we should probably increase the MCMC.interval and try to get a convergent fit with both versions and see if there's an appreciable difference in runtime.

**Comment by chad-klumb** [comment]
Reran both with this modified fit call:

```
> fit_main <- netest(nw_main,
+                    formation = model_main,
+                    target.stats = netstats_main,
+                    coef.diss = netstats$main$diss.byage,
+                    set.control.ergm = control.ergm(MCMLE.maxit = 500,
+                                                    SAN.maxit = 3,
+                                                    SAN.nsteps.times = 3,
+                                                    MCMLE.effectiveSize=NULL,
+                                                    MCMC.samplesize=2000,
+                                                    MCMC.interval=40000,
+                                                    MCMC.burnin=40000),
+                    verbose = FALSE)
```

Both old and new versions converged in 25-30 iterations.

Runtime was 38.60 mins for `dev` and 38.98 mins for the old versions.  (This was running on one core.)  Estimated coefficients were not remarkably different.

A note that the target stats of 0 for `deg3+` and `nodematch(role.class)` do not guarantee that the network SAN produces has zero values for these statistics; e.g., one SAN result had

```
deg3+ nodematch.role.class.0 nodematch.role.class.1 
159                    231                    538 
```

With the SAN changes now in `dev`, using a `-Inf` offset for these statistics should give you a network with zero values for these statistics, which ought to improve the estimation runtime modestly (not as dramatically as for the cohab model, but it should still give some improvement).

**Comment by martinamorris** [comment]
@smjenness from #23 
> These models would fit in ~30 seconds with ergm 3.9. 

I find that statement really surprising.  do you have an install stack that reproduces this?

**Comment by martinamorris** [comment]
> Runtime was 38.60 mins for dev and 38.98 mins for the old versions. 

@chad-klumb are you saying that this model was not fit more quickly with ergm dev, despite the fact that it includes -inf offsets?  Or are you referring to tergmlite dev (in which case, I think we need to start being more clear in writing things up)

**Comment by smjenness** [comment]
I'm sorry - the population size should have been 10k not 100k. I fixed this by changing it to 10k, and was able to go through the workflow as expected. Specifically:

- Estimation of each ERGM took about 30 seconds (as with the previous methods)
- Diagnostics looked fine
- Epidemic simulation appeared to have no degradation in speed or accuracy 

So I think we have a winner! Thanks @chad-klumb!

@martinamorris I'm still unclear why it would take even 7 minutes to estimate your models with a population size of 10k, and would be interested to keep this issue open to see if you can isolate the issue. As a comparison, you can run the `inst/EpiModelHIV.R` script to see the expected speed.

**Comment by martinamorris** [comment]
> I'm still unclear why it would take even 7 minutes to estimate your models with a population size of 10k, and would be interested to keep this issue open to see if you can isolate the issue. As a comparison, you can run the inst/EpiModelHIV.R script to see the expected speed.

@chad-klumb it would be helpful to have you follow up with this.  At this point,  I think the goal is to investigate the speed differences in both msm and het models, comparing ours (WHAMP and SHAMP respectively) to Sam's scripts.   @smjenness is saying that his script estimates using ergm 3.9  take < 1 min, while our working models takes much longer.  There are 3 things to consider/compare:

1. netsizes (10, 20, 50)
2. ergm versions (3.9, dev)
3. models (his scripts with target stats, ours with the ergm.ego workflow)

That's a bunch of cells to fill in.  For the het models, I don't recall if Sam had only 1 network, or 3.  If only 1, we should compare it to our persistent model in SHAMP.

LMK if this makes sense, or if you need more details.

**Comment by chad-klumb** [comment]
The `-Inf` offsets were not used with either.  I was simply saying that specifying `-Inf` offsets would (with `ergm` `dev`, or even `master`) guarantee that SAN respects the constraints being placed on the network, while 0 target stats do not guarantee this.  I don't think it's as big a deal for these models as it was for the cohab model, though.

I can follow up on timing differences, but for the moment I need to focus on stratTNT if I'm going to get it done by next week.

Since Adam was actually the one to run the msm models, it would be helpful to have some input from him (e.g. what scripts and package versions produced the 7 minute fits, and how that time changes with network size).

Differences in data and models may play a large role (e.g. nodematch for small groups in the het models).

**Comment by martinamorris** [comment]
> The -Inf offsets were not used with either. 

either what?  are you saying Sam's scripts for both msm and het did not have -Inf offsets?

this doesn't have to be done now, after stratTNT is fine.  

Adam's scripts are here: https://github.com/statnet/WHAMP/blob/master/adam_work/Darcy_replay/darcy_ee_fits/darcys_terms_artnet_data.rmd 

He's going to be working for Deven on CAMP starting 9/15

**Comment by chad-klumb** [comment]
Either version of `ergm`.

The script used was this one:

https://github.com/EpiModel/CombPrev/blob/master/estimation/estimation.R

It specifies 0 target stats, which "suggests" to SAN that those statistics should have small values, but does not guarantee they are 0.

**Comment by sgoodreau** [comment]
Yeah, @chad-klumb and I chatted through this last point a bit the other day. There are three ways we have to specify that we want to have no ties of a particular type (say, between members of two groups): the constraints argument, an offset term with a coefficient of -Inf, and a regular term with a target stat of 0.  We (certainly Sam and I) often use the term "constraint" to mean all three of those things; Chad had, I think, been interpreting the word to include the first one or two only.

From our conversation it became clear that the work Chad's been doing on SAN covers the first two cases, but he hadn't explicitly worked to have it cover the third, as a result of the above terminology issue.  He's going to look into whether the work he did already automatically covers the third case (unlikely) or what else he would need to do to make it do so.

@smjenness Can you remind us why it is you prefer the third case instead of the second in your modeling work?  If it turns out to be really hard to extend the SAN absolute constraints rule to the third case, would it work to switch to option 2 in practice?

**Comment by smjenness** [comment]
I prefer using target stats because then all the summary stats are listed in a single vector on the same scale; it's not a strong preference, and if necessary to change, I would.

**Comment by smjenness** [comment]
@martinamorris and @chad-klumb : it seems like this was addressed, yes?

**Comment by martinamorris** [comment]
I don't think so.

**Comment by smjenness** [comment]
tergmLite has been disbanded now. @martinamorris : if there are any relevant open sub-issues here, please open new issues on the EpiModel or statnet package repositories.
