### ISSUE TITLE
Diagnose and fix error that nodal attribute is mixing

### ISSUE THREAD

**Issue by sgoodreau** [statnet/tergmLite#26]
@chad-klumb and I have already had a long conversation offline getting to this point.  Short summary is that both @sestansfield's and my evonet scripts stopped working about two weeks ago with the most recent version of all packages, returning an error that a nodal attribute is not present when it clearly is present going into things.  After much sleuthing by Chad and me both, Chad is now almost certain it is due to commit 30a2048, which modified the NAMESPACE, converting what he originally had as `S3method` lines to `export` lines. He and I will meet in person tomorrow to go through things with my whole code base to confirm.

@smjenness, can you clarify the motivation for making this switch?  Does it cause problems for you if we switch back?  The nuances here are a bit above my pay grade so I'll let Chad explain what he thinks the code should be and why. In his words:

"From a software engineering point of view, I do think it is generally frowned upon to export S3 methods using `export`; you're "supposed" to `S3method` them and then call the generic and let it figure things out for you.  The methods can still be accessed directly for testing and debugging using the triple colon ::: operator.  It's also possible `export` and `S3method` don't always behave equivalently when it comes to populating method tables (which might be what we're dealing with here)."

**Comment by smjenness** [comment]
This update to the NAMESPACE was automatic, just running roxygen on the package based on changes Chad made in May 2019. Chad can feel free to update the underlying R code and re-document with roxygen to fix.

**Comment by chad-klumb** [comment]
Interesting; when I run roxygen I get `S3method` lines.

IIRC roxygen's conventions for handling methods did change at some point in the past (not sure how long ago though).  Just curious, what version of roxygen are you running?  I have `roxygen2` version `6.1.1`, which appears to be the current CRAN version.

**Comment by chad-klumb** [comment]
Also, you'd need to have `chad-klumb/network@tergmLiteterms` installed when you `roxygenize` `tergmLite` for it to detect the correspondence between generics and methods correctly (since `list.vertex.attributes` and `get.vertex.attribute` aren't generics in CRAN `network`).  Roxygenizing with CRAN network resulted in ordinary `export` lines.

**Comment by smjenness** [comment]
See https://github.com/statnet/tergmLite/commit/f88fc787111c115175f6dd7f38cc3032a1d1d72c

I think you need to explicitly note the S3 method in roxygen with a `@method` tag. If that looks wrong, please feel free to revert back.

**Comment by chad-klumb** [comment]
I'll test this with Steve when we sit down (presently).

Per Hadley Wickham we're not supposed to use `@method` or `@S3method` anymore (see the top answer here):

https://stackoverflow.com/questions/14361616/s3-method-help-roxygen2

`@export` should work for methods as well as functions, but the correct versions of other packages need to be installed for the correspondence between methods and generics to be recognized.  In this case that means having `chad-klumb/network@tergmLiteterms` rather than CRAN `network` when roxygenizing `tergmLite`.

**Comment by smjenness** [comment]
I see - please revert back then as I likely did not have the proper version of network installed. 

Also, could you move your branch of network over to `statnet/network` in advance of it getting merged into master?

**Comment by chad-klumb** [comment]
I don't have push access to network so I can't do that personally but I'm happy to have someone else do it.

**Comment by smjenness** [comment]
Ok, can you please add that for discussion agenda with @martinamorris when you next meet with her?

**Comment by smjenness** [comment]
Reference back to related workflow issue:

https://github.com/statnet/tergmLite/issues/24#issuecomment-528483629

**Comment by chad-klumb** [comment]
> Ok, can you please add that for discussion agenda with @martinamorris when you next meet with her?

Will do.

@sgoodreau the `tergmLiteterms` branch of `tergmLite` should now work with your code.  Please test at your convenience and let me know if you have any problems.

**Comment by sgoodreau** [comment]
Works, both locally and on Hyak.  Thanks!!!!!
