### ISSUE TITLE
EpiModelHIV.R test "not working"

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergmLite#34]
This does not seem to work with current repo heads (in particular for ARTnet).  I was eventually able to track down past versions for which it now *appears* to be working, but that was a little more complicated than expected as it seems some changes have now been merged into `master` (of ARTnet) that are dated before `EpiModelHIV.R` was posted to tergmLite, and those changes actually break the test.

I am hoping to use this script to get `tergmLite` working with (t)ergm 4.0 but I want to be sure I'm using the appropriate package versions.  If possible, can we update EpiModelHIV.R to work with current repo heads?  I'd hate to get things running with one set of package versions only to find out that it's somehow incompatible with what people are actually using now.

**Comment by martinamorris** [comment]
@smjenness I'll take a quick look at this with @Shmelder today.  I'm guessing the problem is that you've made changes to the ARTnet repo scripts that haven't been integrated into the `EpiModelHIV.R` test script.  Will report back, but I think it would be best if you updated  `EpiModelHIV.R` to be consistent with ARTnet script changes.

**Comment by smjenness** [comment]
Commit b59ee55 locks in the versions of the ARTnet packages that work with this script. At this point, we have a few moving pieces in those packages such that I'm not ready to update the script to use the master branches, but that work will not affect tergm development.
