### ISSUE TITLE
want to track network stats during tergmLite simulation

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergmLite#38]
Sounds like Deven has done this manually before, for one or two statistics.

Emily and I hacked something together that hopefully will allow us to track the full summary stats for the formation models, but it's not optimally efficient.

Ideally, if the user sets a flag, we would get change stats back from the MCMC calls (for little to no additional time cost) and add those to the previous timesteps stats, tracking the network's model term statistics as tergmLite simulation progresses.

We are seeing examples where dynamic netdx looks great but model statistics for the final tergmLite network don't, so that's why we want to get this timestep-by-timestep look at things within tergmLite.

**Comment by chad-klumb** [comment]
Actually just realized changestats from MCMC alone wouldn't take into account changes due to modifications to the network made outside MCMC, so we'd need to do something more/different to get the correct statistics throughout the entire sim.

Calling summary each timestep is possible but may not be optimal.

**Comment by chad-klumb** [comment]
Although doing it differently would seem to require implementing "changestats" for all the sorts of modifications we do outside of MCMC, which is too much work.

So perhaps summary is the way to go.

**Comment by smjenness** [comment]
Hi @chad-klumb : @martinamorris emailed me about this yesterday, and I responded back to her there as follows:

******

If you use save.nwstats = TRUE with EpiModelHIV, it triggers running this:

https://github.com/EpiModel/EpiModelHIV-p/blob/CombPrev/R/mod.simnet.R#L95-L113

which saves 3 network stats (edges, meandeg, concurrent).

Unfortunately,  there is no efficient way to get these summaries on edgelists like you can with network class objects with summary(nw ~ …)

But we also have a general ticket in EpiModel for our EpiModel 2.0 overhaul that includes tergmLite integration to fix this:

https://github.com/statnet/EpiModel/issues/336

I need to write down my idea further there, but it generally consists of passing a vector of time steps to save a sparse network object (edgelist + relevant attributes) and then reconstructing a networkDynamic object after netsim is finished, and then running the network stats as we do now with those objects.

Sam 
********

I think this is actually tergmLite issue rather than an EpiModel issue, so I may close out the issue there. But it is part of our larger overhaul of core EpiModel so I'm going to leave it open and link it for now.

cc: @andsv2

**Comment by smjenness** [comment]
Hi @chad-klumb : any updates on this issue? Thanks

cc: @martinamorris

**Comment by chad-klumb** [comment]
This is available with `tergmLite-private@dev` and `EpiModel@summary_statistics` via the `extract.summary.stats` and `monitors` control arguments.  It can also work with `EpiModelHIV` epidemic simulation as implemented in e.g. `EpiModelHIV@shamp_summary_stats`.

**Comment by smjenness** [comment]
Excellent, thanks. Are these CRAN-compatible with Statnet (ergm, tergm)?

**Comment by chad-klumb** [comment]
As of the most recent updates to those branches of `tergmLite-private` and `EpiModel`, they passed Travis CI when built against `dev` branches of `ergm`, `tergm`, etc.  They do require `dev` versions of various Statnet packages to function properly.

**Comment by smjenness** [comment]
ok, thanks. I will wait to merge tergmLite and EpiModel until the dev vrsions of Statnet packages are published on CRAN. Any idea of the timeline for this?

**Comment by chad-klumb** [comment]
To the best of my knowledge, the current plan is:

1. push current `master` to CRAN in September
2. merge `dev` into `master` soon after 1.
3. give reverse-dependencies and other users a couple of months to adjust to all of the changes introduced from 2.
4. then push `master` (which would include what is currently in `dev`) to CRAN

Based on that, I would expect `dev` to be on CRAN towards the end of this year.

**Comment by smjenness** [comment]
Oh, I thought that was the timeline for the ergm 4.0 packages, and that the dev's were intermediate versions ready to release in August (but we decided to wait until after NME). Is the dev the major 4.0 updates?

**Comment by chad-klumb** [comment]
Yes, `dev` is the major `4.0` updates.

**Comment by martinamorris** [comment]
@chad-klumb this is great, thx.  @smjenness i will start testing the dev versions on WHAMP sims this week.  will keep you updated.

**Comment by smjenness** [comment]
Thank you! @martinamorris : it would be great if we could accelerate step 3 above so that reverse dependency testing does not take 2 months. Any thoughts on how to do that?

**Comment by martinamorris** [comment]
@smjenness this is a major update for the statnet packages -- so i think we all have an interest in thorough testing before release.  the usual practice is 2 wks notice, so i think @chad-klumb's estimate of 2 mos defines the max (and reflects how many packages we will be pushing, and how much time it will take to do that right).

for our crew (the statnet-EpiModel folks),  as always, it's difficult for those in the middle of an existing project to add package update testing to their platter.  but the bottom line is, the more of us testing before release, the better the chance we can release more quickly.

for outside users, we can give them 2 wks, and monitor what happens.  if lots of bug reports start coming in, we'll need to slow down.  if not, we're free to move as quickly as we can get the work done.
