### ISSUE TITLE
segfault in simulate_network with control = NULL

### ISSUE THREAD

**Issue by AdrienLeGuillou** [statnet/tergmLite#55]
when implementing the new APIs for the CombPrevNet project I stumbled upon a segfault in the `tergmLite::simulate_network` [here](https://github.com/EpiModel/EpiModelHIV-p/blob/CPN_new_APIs/R/mod.simnet.R#L27).

This was due to the `reinit_msm` function not pulling the `mcmc.control` element from the original `simnet` object. ( [fixed here](https://github.com/EpiModel/EpiModelHIV-p/blob/CPN_new_APIs/R/mod.initialize.R#L402-L405) )

So now it works fine but I suppose we should have an error in such a case and not a segfault with R completely crashing. The segfault itself happens in the call of `tergm_MCMC_slave`, [specifically here](https://github.com/statnet/tergm/blob/f79e62d42f1cce95a0bbe51bf6f19d50c83ca635/R/tergm.getMCMCsample.R#L121-L139)

**Comment by chad-klumb** [comment]
One option is to add a `check.control.class` call to `simulate_network` and `simulate_ergm`, which if passed `NULL` would produce an error message like

```
Error in UseMethod("as.control.list") : 
  no applicable method for 'as.control.list' applied to an object of class "NULL"
```

This isn't quite a perfect check because the `simulate_network` and `simulate_ergm` controls actually need some augmentation beyond the arguments supported by the corresponding statnet control functions.

These issues should be obviated by moving to top level simulate functions, which use non-augmented control arguments and perform control class checks.

**Comment by AdrienLeGuillou** [comment]
I'll close the issue then if this will disappear with the move to top level simulate functions. Thanks!
