### ISSUE TITLE
New errors with EpiModel v2.3.0

### ISSUE THREAD

**Issue by smjenness** [statnet/tergmLite#56]
There are new errors arising from the publication of EpiModel v2.3.0 on CRAN. 
https://cran.r-project.org/web/checks/check_results_tergmLite.html

@chad-klumb : could you check these and update the unit tests as necessary. At a minimum, we can use some conditional logic to only test if EpiModel v is < 2.3.0. 

I'd like to keep tergmLite up on CRAN for the time being in case any users are still using older versions of EpiModel.

**Comment by chad-klumb** [comment]
tergmLite really shouldn't be built and tested with new versions of EpiModel (or statnet packages, for that matter); it isn't designed or maintained to be compatible with them

the immediate issue here seems to be that the old tergmLite implementation of networkLites uses matrices for edgelists, while the newer EpiModel implementation uses tibbles, and these aren't interchangeable

since tergmLite is supposed to work with an older set of packages (where matrix edgelists are appropriate and probably required), we shouldn't change the implementation in tergmLite

restricting to legacy versions of EpiModel and/or removing the tests entirely would be my suggestion, with something of a preference for the latter, since we don't really want CRAN running these checks ever again

in principle it is also possible for examples to start failing if packages evolve enough, so we might want to skip or remove those as well

anything against just deleting/skipping the tests and examples?

**Comment by smjenness** [comment]
Fine with me to skip/delete

**Comment by chad-klumb** [comment]
went with skipping for now
